OSM_SOURCES = {
    # --- Original Test/Country Sets ---
    "monaco": "https://download.geofabrik.de/europe/monaco-latest.osm.pbf",
    "liechtenstein": "https://download.geofabrik.de/europe/liechtenstein-latest.osm.pbf",
    "germany": "https://download.geofabrik.de/europe/germany-latest.osm.pbf",
    "france": "https://download.geofabrik.de/europe/france-latest.osm.pbf",
    "italy": "https://download.geofabrik.de/europe/italy-latest.osm.pbf",
    "spain": "https://download.geofabrik.de/europe/spain-latest.osm.pbf",
    "uk": "https://download.geofabrik.de/europe/great-britain-latest.osm.pbf",
    "usa": "https://download.geofabrik.de/north-america/us-latest.osm.pbf",
    "canada": "https://download.geofabrik.de/north-america/canada-latest.osm.pbf",

    # --- Middle East Countries ---
    "bahrain": "https://download.geofabrik.de/asia/gcc-states-latest.osm.pbf", # Often bundled in GCC
    "iran": "https://download.geofabrik.de/asia/iran-latest.osm.pbf",
    "iraq": "https://download.geofabrik.de/asia/iraq-latest.osm.pbf",
    "israel-palestine": "https://download.geofabrik.de/asia/israel-and-palestine-latest.osm.pbf",
    "jordan": "https://download.geofabrik.de/asia/jordan-latest.osm.pbf",
    "kuwait": "https://download.geofabrik.de/asia/gcc-states-latest.osm.pbf",
    "lebanon": "https://download.geofabrik.de/asia/lebanon-latest.osm.pbf",
    "oman": "https://download.geofabrik.de/asia/gcc-states-latest.osm.pbf",
    "qatar": "https://download.geofabrik.de/asia/gcc-states-latest.osm.pbf",
    "saudi-arabia": "https://download.geofabrik.de/asia/gcc-states-latest.osm.pbf",
    "syria": "https://download.geofabrik.de/asia/syria-latest.osm.pbf",
    "turkey": "https://download.geofabrik.de/europe/turkey-latest.osm.pbf", # Note: In Europe dir
    "uae": "https://download.geofabrik.de/asia/gcc-states-latest.osm.pbf",
    "yemen": "https://download.geofabrik.de/asia/yemen-latest.osm.pbf",

    # --- US States & Territories ---
    "alabama": "https://download.geofabrik.de/north-america/us/alabama-latest.osm.pbf",
    "alaska": "https://download.geofabrik.de/north-america/us/alaska-latest.osm.pbf",
    "arizona": "https://download.geofabrik.de/north-america/us/arizona-latest.osm.pbf",
    "arkansas": "https://download.geofabrik.de/north-america/us/arkansas-latest.osm.pbf",
    "california": "https://download.geofabrik.de/north-america/us/california-latest.osm.pbf",
    "colorado": "https://download.geofabrik.de/north-america/us/colorado-latest.osm.pbf",
    "connecticut": "https://download.geofabrik.de/north-america/us/connecticut-latest.osm.pbf",
    "delaware": "https://download.geofabrik.de/north-america/us/delaware-latest.osm.pbf",
    "district-of-columbia": "https://download.geofabrik.de/north-america/us/district-of-columbia-latest.osm.pbf",
    "florida": "https://download.geofabrik.de/north-america/us/florida-latest.osm.pbf",
    "georgia": "https://download.geofabrik.de/north-america/us/georgia-latest.osm.pbf",
    "hawaii": "https://download.geofabrik.de/north-america/us/hawaii-latest.osm.pbf",
    "idaho": "https://download.geofabrik.de/north-america/us/idaho-latest.osm.pbf",
    "illinois": "https://download.geofabrik.de/north-america/us/illinois-latest.osm.pbf",
    "indiana": "https://download.geofabrik.de/north-america/us/indiana-latest.osm.pbf",
    "iowa": "https://download.geofabrik.de/north-america/us/iowa-latest.osm.pbf",
    "kansas": "https://download.geofabrik.de/north-america/us/kansas-latest.osm.pbf",
    "kentucky": "https://download.geofabrik.de/north-america/us/kentucky-latest.osm.pbf",
    "louisiana": "https://download.geofabrik.de/north-america/us/louisiana-latest.osm.pbf",
    "maine": "https://download.geofabrik.de/north-america/us/maine-latest.osm.pbf",
    "maryland": "https://download.geofabrik.de/north-america/us/maryland-latest.osm.pbf",
    "massachusetts": "https://download.geofabrik.de/north-america/us/massachusetts-latest.osm.pbf",
    "michigan": "https://download.geofabrik.de/north-america/us/michigan-latest.osm.pbf",
    "minnesota": "https://download.geofabrik.de/north-america/us/minnesota-latest.osm.pbf",
    "mississippi": "https://download.geofabrik.de/north-america/us/mississippi-latest.osm.pbf",
    "missouri": "https://download.geofabrik.de/north-america/us/missouri-latest.osm.pbf",
    "montana": "https://download.geofabrik.de/north-america/us/montana-latest.osm.pbf",
    "nebraska": "https://download.geofabrik.de/north-america/us/nebraska-latest.osm.pbf",
    "nevada": "https://download.geofabrik.de/north-america/us/nevada-latest.osm.pbf",
    "new-hampshire": "https://download.geofabrik.de/north-america/us/new-hampshire-latest.osm.pbf",
    "new-jersey": "https://download.geofabrik.de/north-america/us/new-jersey-latest.osm.pbf",
    "new-mexico": "https://download.geofabrik.de/north-america/us/new-mexico-latest.osm.pbf",
    "new-york": "https://download.geofabrik.de/north-america/us/new-york-latest.osm.pbf",
    "north-carolina": "https://download.geofabrik.de/north-america/us/north-carolina-latest.osm.pbf",
    "north-dakota": "https://download.geofabrik.de/north-america/us/north-dakota-latest.osm.pbf",
    "ohio": "https://download.geofabrik.de/north-america/us/ohio-latest.osm.pbf",
    "oklahoma": "https://download.geofabrik.de/north-america/us/oklahoma-latest.osm.pbf",
    "oregon": "https://download.geofabrik.de/north-america/us/oregon-latest.osm.pbf",
    "pennsylvania": "https://download.geofabrik.de/north-america/us/pennsylvania-latest.osm.pbf",
    "rhode-island": "https://download.geofabrik.de/north-america/us/rhode-island-latest.osm.pbf",
    "south-carolina": "https://download.geofabrik.de/north-america/us/south-carolina-latest.osm.pbf",
    "south-dakota": "https://download.geofabrik.de/north-america/us/south-dakota-latest.osm.pbf",
    "tennessee": "https://download.geofabrik.de/north-america/us/tennessee-latest.osm.pbf",
    "texas": "https://download.geofabrik.de/north-america/us/texas-latest.osm.pbf",
    "utah": "https://download.geofabrik.de/north-america/us/utah-latest.osm.pbf",
    "vermont": "https://download.geofabrik.de/north-america/us/vermont-latest.osm.pbf",
    "virginia": "https://download.geofabrik.de/north-america/us/virginia-latest.osm.pbf",
    "washington": "https://download.geofabrik.de/north-america/us/washington-latest.osm.pbf",
    "west-virginia": "https://download.geofabrik.de/north-america/us/west-virginia-latest.osm.pbf",
    "wisconsin": "https://download.geofabrik.de/north-america/us/wisconsin-latest.osm.pbf",
    "wyoming": "https://download.geofabrik.de/north-america/us/wyoming-latest.osm.pbf",
    
    # Territories
    "puerto-rico": "https://download.geofabrik.de/north-america/us/puerto-rico-latest.osm.pbf",
    "american-samoa": "https://download.geofabrik.de/australia-oceania/american-samoa-latest.osm.pbf",
    "guam": "https://download.geofabrik.de/australia-oceania/guam-latest.osm.pbf",
}